In [24]:
import sys
sys.path.append("..")
from common.util import *

text = "You say goodbye and i say hello."
corpus, word_to_id, id_to_word = preprocess(text)   # 텍스트 전처리:  corpus
vocab_size = len(word_to_id)    # 단어 개수 for 행렬 크기 설정
co_matrix = create_co_matrix(corpus, vocab_size)
ppmi_matrix = ppmi(co_matrix, verbose = False)


c_you = co_matrix[word_to_id["you"]]
c_i = co_matrix[word_to_id["i"]]

print(cos_similarity(c_you, c_i))


0.7071067691154799


In [25]:
print(co_matrix)
most_similar("you", word_to_id, id_to_word, co_matrix, top=5)

[[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]

[query] you
 goodbye: 0.7071067691154799
 i: 0.7071067691154799
 hello: 0.7071067691154799
 say: 0.0
 and: 0.0


In [28]:
print(ppmi_matrix)
most_similar("you", word_to_id, id_to_word, ppmi_matrix, top=5)

[[0.        1.8073549 0.        0.        0.        0.        0.       ]
 [1.8073549 0.        0.8073549 0.        0.8073549 0.8073549 0.       ]
 [0.        0.8073549 0.        1.8073549 0.        0.        0.       ]
 [0.        0.        1.8073549 0.        1.8073549 0.        0.       ]
 [0.        0.8073549 0.        1.8073549 0.        0.        0.       ]
 [0.        0.8073549 0.        0.        0.        0.        2.807355 ]
 [0.        0.        0.        0.        0.        2.807355  0.       ]]

[query] you
 goodbye: 0.40786147117614746
 i: 0.40786147117614746
 hello: 0.2763834297657013
 say: 0.0
 and: 0.0


In [29]:
# 차원 줄이기(by SVD)
U, S, V = np.linalg.svd(ppmi_matrix)

print(U.shape)
print(S.shape)  # 대각행렬이여서 1차원으로도 저장 가능
print(V.shape)

(7, 7)
(7,)
(7, 7)
